NTierProje/NTierProje.UI/Areas/Admin/Controllers/AppUserController.cs
using NTier.Model.Entities;
using NTier.Service.Option;
using NTierProje.UI.Attributes;
using NTierProje.UI.Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTierProje.UI.Areas.Admin.Controllers
{
    [CustomAuthorize(Role.Admin)]
    public class AppUserController : Controller
    {
        AppUserService _appUserService;
        public AppUserController()
        {
            _appUserService = new AppUserService();
        }

        // GET: Admin/AppUser
        public ActionResult List(int page = 1)
        {
            List<AppUser> model = _appUserService.GetActive();
            
            return View(model.ToPagedList(page,10));
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AppUser data,HttpPostedFileBase Image)
        {
            data.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/", Image);

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
                data.ImagePath = "~/Content/Image/close_1.png";

            _appUserService.Add(data);

            return View();
        }

        public ActionResult Update(Guid id)
        {
            return View(_appUserService.GetById(id));
        }

        [HttpPost]
        public ActionResult Update(AppUser data,HttpPostedFileBase Image)
        {
            data.ImagePath = ImageUploader.UploadSingleImage("~/Uploads/", Image);

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {
                AppUser updated = _appUserService.GetById(data.Id);
                if (updated.ImagePath == null || updated.ImagePath == "~/Content/Image/close_1.png")
                {
                    data.ImagePath = "~/Content/Image/close_1.png";
                }
                else
                {
                    data.ImagePath = updated.ImagePath;
                }
            }

            _appUserService.Update(data);

            return Redirect("/Admin/AppUser/List");
        }

        public RedirectResult Delete(Guid id)
        {
            _appUserService.Remove(id);
            return Redirect("/Admin/AppUser/List");
        }
    }
}

NTierProje/NTierProje.UI/Areas/Admin/Views/AppUser/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}
´<form action="/Admin/AppUser/Add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Name">Ismi</label>
        <input type="text" name="Name" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="SurName">Soyismi</label>
        <input type="text" name="Surname" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="PhoneNumber">Telefon No</label>
        <input type="text" name="PhoneNumber" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Adress">Adres</label>
        <input type="text" name="Address" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input type="text" name="Email" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Image">Fotoğraf</label>
        <input type="file" name="Image" value="" />
    </div>
    <div class="form-group">
        <label for="UserName">Kullanıcı Adı</label>
        <input type="text" name="UserName" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Password">Password</label>
        <input type="text" name="Password" value="" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Role">Rol</label>
        <select name="Role">
            @foreach (var item in Enum.GetNames(typeof(NTier.Model.Entities.Role)))
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>
    <input type="submit" name="name" value="Ekle" class="form-control btn btn-primary" />
</form>

NTierProje/NTierProje.UI/Areas/Admin/Views/AppUser/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}
@using PagedList;
@using PagedList.Mvc

@model IPagedList<NTier.Model.Entities.AppUser>
<div class="col-md-12">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Kullanıcı İsmi</th>
                <th>Kullanıcı Soyismi</th>
                <th>UserName</th>
                <th>Password</th>
                <th>Telefon Numarası</th>
                <th>Adres</th>
                <th>Email</th>
                <th>Rol</th>
                <th>Fotoğraf</th>
                <th colspan="2">Güncelle / Sil</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.SurName</td>
                    <td>@item.UserName</td>
                    <td>@item.Password</td>
                    <td>@item.PhoneNumber</td>
                    <td>@item.Adress</td>
                    <td>@item.Email</td>
                    <td>@item.Role</td>
                    <td><img src="@item.ImagePath" style="display:block;" width="30" height="30" /></td>
                    <td>
                        <a href="/Admin/AppUser/update/@item.Id">Güncelle</a>
                        /
                        <a href="/Admin/AppUser/delete/@item.Id">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagedList">
        @Html.PagedListPager(Model, page => Url.Action("List", "AppUser", new { page }), PagedListRenderOptions.Classic)
    </div>
</div>

NTierProje/NTierProje.UI/Areas/Admin/Views/AppUser/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_SharedAdminLayout.cshtml";
}
@model NTier.Model.Entities.AppUser
<form action="/Admin/AppUser/Update" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Name">Ismi</label>
        <input type="text" name="Name" value="@Model.Name" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Surname">Soyismi</label>
        <input type="text" name="Surname" value="@Model.SurName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="UserName">Kullanıcı Adı</label>
        <input type="text" name="UserName" value="@Model.UserName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Password">Şifre</label>
        <input type="text" name="Password" value="@Model.Password" class="form-control" />
    </div>
    <div class="form-group">
        <label for="PhoneNumber">Telefon No</label>
        <input type="text" name="PhoneNumber" value="@Model.PhoneNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Address">Adres</label>
        <input type="text" name="Address" value="@Model.Adress" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input type="text" name="Email" value="@Model.Email" class="form-control" />
    </div>
    <div class="form-control">
        <label for="Role">Rol</label>
        <select name="Role">
            @foreach (var item in Enum.GetNames(typeof(NTier.Model.Entities.Role)))
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>
    <div class="form-group">
        <img style="display:block;" width="30" height="30" src="@Model.ImagePath" />
        <label for="Image">Fotoğraf Seçiniz</label>
        <input type="file" name="Image" value="" />
    </div>

    @Html.HiddenFor(x => x.Id)
    <input type="submit" name="name" value="Güncelle" class="form-control btn btn-primary" />
</form>